[package]
name = "spectre-core"
version = "0.0.1"
edition = "2021"
authors = ["Xevrac"]
description = "Core logic for Spectre"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
image = "0.24"

